Last login: Sun Apr  8 00:50:47 on ttys000
airbears2-10-142-151-141:~ fuyuwei$ cd downloads/cs61a/scheme
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 -u
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Unlocking tests

At each "? ", type what you would expect the output to be.
Type exit() to quit

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1
(cases remaining: 6)

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
Choose the number of the correct choice:
0) SchemeError
1) (2)
2) 2
? 1
-- OK! --

>>> eval_all(Pair(4, Pair(5, nil)), env)
Choose the number of the correct choice:
0) SchemeError
1) 5
2) (4)
3) 4
4) (5)
? 4
-- OK! --

>>> eval_all(nil, env) # return None (meaning undefined)
---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 2
(cases remaining: 5)

-- Already unlocked --

---------------------------------------------------------------------
Problem 8 > Suite 2 > Case 1
(cases remaining: 4)


scm> (begin (+ 2 3) (+ 5 6))
? 11
-- OK! --

scm> (begin (define x 3) x)
? 3
-- OK! --

---------------------------------------------------------------------
Problem 8 > Suite 2 > Case 2
(cases remaining: 3)


scm> (begin 30 '(+ 2 2))
Choose the number of the correct choice:
0) 4
1) (+ 2 2)
2) 30
3) '(+ 2 2)
? `
-- Not quite. Try again! --

Choose the number of the correct choice:
0) 4
1) (+ 2 2)
2) 30
3) '(+ 2 2)
? 1
-- OK! --

scm> (define x 0)
? x
-- OK! --

scm> (begin 42 (define x (+ x 1)))
? x
-- OK! --

scm> x
? 1
-- OK! --

---------------------------------------------------------------------
Problem 8 > Suite 2 > Case 3
(cases remaining: 2)

-- Already unlocked --

---------------------------------------------------------------------
Problem 8 > Suite 2 > Case 4
(cases remaining: 1)

-- Already unlocked --

---------------------------------------------------------------------
OK! All cases for Problem 8 unlocked.

ERROR  | auth.py:91 | {'error': 'invalid_grant'}
Performing authentication
Please enter your bCourses email.
bCourses email: fuyuwei@berkeley.edu
Successfully logged in as fuyuwei@berkeley.edu
Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ open scheme.py
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 59, in eval_all
    return scheme_eval(expressions, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 36, in scheme_eval
    return scheme_apply(procedure, args, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 46, in scheme_apply
    check_procedure(procedure)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 361, in check_procedure
    type(procedure).__name__.lower(), repl_str(procedure)))
scheme_primitives.SchemeError: int is not callable: 2

# Error: expected
#     2
# but got
#     Traceback (most recent call last):
#       ...
#     SchemeError: int is not callable: 2

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 58, in eval_all
    return scheme_eval(expressions.second, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 36, in scheme_eval
    return scheme_apply(procedure, args, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 46, in scheme_apply
    check_procedure(procedure)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 361, in check_procedure
    type(procedure).__name__.lower(), repl_str(procedure)))
scheme_primitives.SchemeError: int is not callable: 5

# Error: expected
#     5
# but got
#     Traceback (most recent call last):
#       ...
#     SchemeError: int is not callable: 5

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)

# Error: expected
#     2
# but got


Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 59, in eval_all
    return scheme_eval(expressions.second, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 36, in scheme_eval
    return scheme_apply(procedure, args, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 46, in scheme_apply
    check_procedure(procedure)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 362, in check_procedure
    type(procedure).__name__.lower(), repl_str(procedure)))
scheme_primitives.SchemeError: int is not callable: 5

# Error: expected
#     5
# but got
#     Traceback (most recent call last):
#       ...
#     SchemeError: int is not callable: 5

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 59, in eval_all
    return scheme_eval(expressions.second, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 36, in scheme_eval
    return scheme_apply(procedure, args, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 46, in scheme_apply
    check_procedure(procedure)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 362, in check_procedure
    type(procedure).__name__.lower(), repl_str(procedure)))
scheme_primitives.SchemeError: int is not callable: 5

# Error: expected
#     5
# but got
#     Traceback (most recent call last):
#       ...
#     SchemeError: int is not callable: 5

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
4

# Error: expected
#     5
# but got
#     4

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 59, in eval_all
    return scheme_eval(expressions.second, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 36, in scheme_eval
    return scheme_apply(procedure, args, env)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 46, in scheme_apply
    check_procedure(procedure)
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 362, in check_procedure
    type(procedure).__name__.lower(), repl_str(procedure)))
scheme_primitives.SchemeError: int is not callable: 5

# Error: expected
#     5
# but got
#     Traceback (most recent call last):
#       ...
#     SchemeError: int is not callable: 5

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
5
>>> eval_all(nil, env) # return None (meaning undefined)
Traceback (most recent call last):
  File "/Users/fuyuwei/Downloads/CS61A/scheme/scheme.py", line 57, in eval_all
    scheme_eval(expressions.first, env)
AttributeError: 'nil' object has no attribute 'first'

# Error: expected

# but got
#     Traceback (most recent call last):
#       ...
#     AttributeError: 'nil' object has no attribute 'first'

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 1 > Case 1

>>> from scheme import *
>>> env = create_global_frame()
>>> eval_all(Pair(2, nil), env)
2
>>> eval_all(Pair(4, Pair(5, nil)), env)
5
>>> eval_all(nil, env) # return None (meaning undefined)
nil

# Error: expected

# but got
#     nil

Run only this test case with "python3 ok -q 08 --suite 1 --case 1"
---------------------------------------------------------------------
Test summary
    0 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Problem 8 > Suite 2 > Case 2

scm> (begin 30 '(+ 2 2))
(+ 2 2)
scm> (define x 0)
x
scm> (begin 42 (define x (+ x 1)))
x
scm> x
2

# Error: expected
#     1
# but got
#     2

Run only this test case with "python3 ok -q 08 --suite 2 --case 2"
---------------------------------------------------------------------
Test summary
    3 test cases passed before encountering first failed test case

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ python3 ok -q 08 
=====================================================================
Assignment: Project 4: Scheme Interpreter
OK, version v1.13.11
=====================================================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Running tests

---------------------------------------------------------------------
Test summary
    6 test cases passed! No cases failed.

Backup... 100% complete
Backup successful for user: fuyuwei@berkeley.edu

Checking for software updates...
OK is up to date
airbears2-10-142-151-141:scheme fuyuwei$ 
